version: "3.9"

services:

  servidor:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: luizmiguelvb/servidor
    container_name: servidor
    ports:
      - "8081:8081"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    networks:
      - gestao-mercados-microsservices-bridge

networks:
  gestao-mercados-microsservices-bridge:
    name: "gestao-mercados-microsservices-bridge"
    driver: bridge
    external: true