server:
  port: 8081

spring:
  application:
    name: servidor

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://servidor:8081/eureka